### ISSUE TITLE
We are installing only go-server on the AMI box, can we also install go-agent along ?

### ISSUE THREAD

**Issue by karthikcru** [gocd/gocd-cloud#3]
https://github.com/gocd/gocd-cloud/blob/9b1ecea31f5f22a68178a641f62d31f8c7302814/go-server-packer.json#L59

**Comment by ketan** [comment]
While possible, I don't feel strongly about doing that. For production instances, it's advisable that you use a separate server for an agent and server.

If you need to install a go agent, it should be as easy as `yum install -y go-agent` in your user data script.

Alternatively, you may use the GoCD demo instance that contains the server and agent installed on it. It comes pre-packaged with an example configuration, but you should be able to use your own configuration instead.

**Comment by karthikcru** [comment]
That makes sense, I tried to start the go-agents on the same box and I had to install the go-agent.

I was misguided by this on the ami page 

`This AMI is for users to get started with GoCD. It contains both GoCD server and agent with an existing configuration.`

Thanks for the help
